
package mypackage;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService1Soap {


    /**
     * 
     * @param amount
     * @param from
     * @param to
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "ConvertCurrency", action = "http://tempuri.org/ConvertCurrency")
    @WebResult(name = "ConvertCurrencyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertCurrency", targetNamespace = "http://tempuri.org/", className = "mypackage.ConvertCurrency")
    @ResponseWrapper(localName = "ConvertCurrencyResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.ConvertCurrencyResponse")
    public BigDecimal convertCurrency(
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        String from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        String to);

}
