# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - frontend2

on:
  push:
    branches:
      - rest.implementation
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0fddf1023c72482d87027016e725c47e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_97df99598e464f45913420a9eb54ce35 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0fddf1023c72482d87027016e725c47e }}/jerreeey/frontend:${{ github.sha }}
        file: ./Frontend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frontend2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_134714baca094269b1ad7035ae395a2a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0fddf1023c72482d87027016e725c47e }}/jerreeey/frontend:${{ github.sha }}'
